routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    dd(\Carbon\Carbon::now()->format('Y-m-d H:i a'));
});

Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/', 'PagesController@index');
Route::get('/contact', 'PagesController@contact');
Route::post('/contact', 'PagesController@storeContact');
Route::get('/about', 'PagesController@about');
Route::get('/blog', 'PostsController@index');
Route::get('/blog/{id}', 'PostsController@show');
Route::get('/privacy-policy', 'PagesController@privacyPolicy');
Route::get('/credits', 'PagesController@credits');
Route::get('/services', 'PagesController@services');
Route::get('/majors', 'PagesController@majors');
Route::get('/privacy-policy', 'PagesController@privacyPolicy');
Route::get('/faqs', 'PagesController@faqs');

//Route::get('/team', 'PagesController@team');

Route::get('/doctors/create', 'DoctorsController@create')->middleware(['throttle:10', 'guest']);
Route::post('/doctors/create', 'DoctorsController@store')->middleware(['throttle:10', 'guest']);
Route::post('/doctors/uploadImagesStore', 'DoctorsController@uploadImagesStore')->middleware(['throttle:10', 'guest']);
Route::get('/doctors/listDoctorImages', 'DoctorsController@listDoctorImages')->middleware(['auth', 'roles:doctor']);
Route::post('/doctors/uploadImagesUpdate', 'DoctorsController@uploadImagesUpdate')->middleware(['auth', 'roles:doctor']);
Route::delete('/doctors/deleteImage', 'DoctorsController@DeleteImage');

Route::get('/listings', 'ListingsController@index');
Route::get('/reservation', 'ListingsController@reservation');
Route::post('/reserve', 'ListingsController@reserve')->middleware(['throttle:3']);
Route::get('/doctors/{doctor}', 'DoctorsController@show');


Route::post('/user/bookings/cancel/{booking}', 'CustomersController@cancel')->middleware(['auth', 'roles:customer']);
Route::post('/user/review/{doctor}', 'CustomersController@review')->middleware(['auth', 'roles:customer']);
Route::get('/user/bookings', 'CustomersController@bookings')->middleware(['auth', 'roles:customer']);

Route::group(['middleware' => ['auth', 'roles:doctor']], function(){
    Route::get('/schedule', 'DoctorsController@schedule');
    Route::post('/schedule', 'DoctorsController@scheduleStore');
    Route::get('/profile', 'DoctorsController@profile');
    Route::post('/profile', 'DoctorsController@update');
    Route::get('/bookings', 'DoctorsController@bookings');
    Route::post('/bookings/cancel/{booking}', 'DoctorsController@cancel');
    Route::get('/dashboard', 'DoctorsController@dashboard');
    Route::get('/change-password', 'DoctorsController@change-password');
});



Route::group(['prefix' => 'admin','middleware' => ['auth', 'roles:admin'], 'as' => 'admin.'], function() {

    Route::get('/', function () {
        return redirect('/admin/home');
    });

    Route::get('/home', 'admin\HomeController@index')->name('home');

    //  admin users routes
    Route::get('/users/getData', 'admin\UsersController@getUsersData');
    Route::get('/change-password','admin\UsersController@changePassword');
    Route::post('/change-password','admin\UsersController@changePasswordStore');
    Route::get('/users/listDoctorImages', 'admin\UsersController@listDoctorImages');
    Route::post('/users/uploadImagesStore', 'admin\UsersController@uploadImagesStore');
    Route::post('/users/uploadImagesUpdate', 'admin\UsersController@uploadImagesUpdate');
    Route::delete('/users/deleteImage', 'admin\UsersController@DeleteImage');
    Route::get('users/{user}/activation','admin\UsersController@activation');
    Route::resource('users','admin\UsersController');

    Route::get('/doctors/getData', 'admin\DoctorsController@getDoctorsData');
    Route::delete('/doctors/deleteImage', 'admin\DoctorsController@DeleteImage');
    Route::get('/doctors/listEventImages', 'admin\DoctorsController@listDoctorImages');
    Route::post('/doctors/uploadImagesStore', 'admin\DoctorsController@uploadImagesStore');
    Route::post('/doctors/uploadImagesUpdate', 'admin\DoctorsController@uploadImagesUpdate');
    Route::get('/doctors/{doctor}/activation/{action?}','admin\DoctorsController@approved');
    Route::resource('doctors','admin\DoctorsController');

    Route::get('/offices/getData', 'admin\OfficesController@getOfficesData');
    Route::resource('offices','admin\OfficesController');

    Route::get('/customers/getData', 'admin\CustomersController@getCustomersData');
    Route::resource('customers','admin\CustomersController');

    Route::get('/bookings/export','admin\BookingsController@export');
    Route::get('/bookings/getData', 'admin\BookingsController@getBookingsData');
    Route::get('/bookings/{booking}/activation/{action?}','admin\BookingsController@approved');
    Route::post('/bookings/{booking}/changeStatus/{change_to}','admin\BookingsController@changeStatus');
    Route::post('/bookings/{booking}/changeVisitStatus/{change_to}','admin\BookingsController@changeVisitStatus');
    Route::post('/bookings/{booking}/changeProcedure/{change_to}','admin\BookingsController@changeProcedure');

    Route::post('/bookings/{booking}/confirmPatient/{change_to}','admin\BookingsController@confirmPatient');
    Route::post('/bookings/{booking}/confirmInvoiced/{change_to}','admin\BookingsController@confirmInvoiced');
    Route::resource('bookings','admin\BookingsController');

    Route::get('/contacts/getData', 'admin\ContactsController@getContactsData');
    Route::delete('/contacts/{contact}', 'admin\ContactsController@destroy');
    Route::get('/contacts', 'admin\ContactsController@index');

    Route::get('/posts/getData', 'admin\PostsController@getPostsData');
    Route::resource('/posts', 'admin\PostsController');
    Route::get('posts/{post}/activation', 'admin\PostsController@activation');
    Route::get('posts/{post}/featured', 'admin\PostsController@featured');

    //    admin categories routes
    Route::get('/categories/getData', 'admin\CategoriesController@getCategoriesData');
    Route::resource('categories','admin\CategoriesController', ['except' => [
        'show'
    ]]);

    Route::get('/majors/getData', 'admin\MajorsController@getMajorsData');
    Route::resource('/majors', 'admin\MajorsController');
    Route::get('/majors/{major}/visibility/{action?}','admin\MajorsController@visibility');


    Route::get('/services/getData', 'admin\ServicesController@getServicesData');
    Route::resource('/services', 'admin\ServicesController');

    Route::get('/faqs/getData', 'admin\FaqsController@getFaqsData');
    Route::resource('/faqs', 'admin\FaqsController');

    Route::get('/insurances/getData', 'admin\InsurancesController@getInsurancesData');
    Route::resource('/insurances', 'admin\InsurancesController');

    Route::get('/procedures/getData', 'admin\ProceduresController@getProceduresData');
    Route::resource('/procedures', 'admin\ProceduresController');

    Route::get('/regions/getData', 'admin\RegionsController@getRegionsData');
    Route::resource('/regions', 'admin\RegionsController');
    Route::get('regions/{region}/toggleShown', 'admin\RegionsController@toggleShown');


    Route::get('/reviews/getData', 'admin\ReviewsController@getReviewsData');
    Route::resource('/reviews', 'admin\ReviewsController', ['only', ['index', 'destroy']]);
    Route::get('/reviews/{review}/change-status/{action?}/{value?}','admin\ReviewsController@changeStatus');

    Route::get('/pictures/listPicturesByCat', 'admin\PicturesController@listPicturesByCat');
    Route::get('/pictures/listPictureById', 'admin\PicturesController@listPictureById');
    Route::post('/pictures/uploadedImagesUpdateInfo', 'admin\PicturesController@uploadedImagesUpdateInfo');
    Route::delete('/pictures/deleteImage', 'admin\PicturesController@DeleteImage');
    Route::get('/pictures/getData', 'admin\PicturesController@getPicturesData');
    Route::resource('/pictures', 'admin\PicturesController')->only([
        'index', 'show', 'create', 'destroy'
    ]);;
    Route::post('/pictures/uploadImagesStore', 'admin\PicturesController@uploadImagesStore');


    Route::get('/contents', 'admin\ContentsController@show');
    Route::get('/contents/edit', 'admin\ContentsController@edit');
    Route::post('/contents/', 'admin\ContentsController@update');

    Route::get('/image-contents', 'admin\ImageContentsController@show');
    Route::post('/image-contents/', 'admin\ImageContentsController@update');

    Route::get('/settings', 'admin\SettingsController@edit');
    Route::post('/settings/', 'admin\SettingsController@update');


});

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Session;

class Post extends Model
{
    use StatisticsFunctions;
    protected $with = ['category'];
    protected $fillable = [
        "title_en",
        "title_ar",
        "body_en",
        "body_ar",
        "status",
        "type",
        "picture"
    ];
    public static $TYPE_NORMAL_POST = 0;
    public static $TYPE_FEATURED_POST = 1;
    public static $LIMIT_FEATURED_POSTS = 4;

    public function category()
    {
        return $this->belongsTo('App\Category');
    }
    public function getCategoryName()
    {
        if ($category = $this->category){
            return $category->name_ar;
        }
        return '';
    }

    public function path($admin = null){
        if($admin){
            return '/admin/posts/' . $this->id;
        }
        return '/blog/' . $this->id;
    }
    public function togglePublished(){
        if ($this->status){
            $this->status = 0;
            Session::flash('toast','Post is unpublished');
        }
        else{
            $this->status = 1;
            Session::flash('toast','Post is published');
        }
        $this->save();
    }
    public function toggleFeatured(){
        if ($this->type == static::$TYPE_FEATURED_POST){// if post is featured post
            $this->type = static::$TYPE_NORMAL_POST;
            Session::flash('toast', ['Post is not featured anymore', 'success']);
        }
        else if ($this->type == static::$TYPE_NORMAL_POST){
            if (static::where('type', static::$TYPE_FEATURED_POST)->count() >= static::$LIMIT_FEATURED_POSTS){ // if there are more than 4 featured posts
                Session::flash('toast', ['You cant have more than ' . static::$LIMIT_FEATURED_POSTS . ' featured posts', 'error']);
                return;
            }
            if (! $this->picture) {
                Session::flash('toast', ['A featured post must have an image', 'error']);
                return;
            }
            $this->type = static::$TYPE_FEATURED_POST;
            Session::flash('toast', ['Post will now appear in the home page blog', 'success']);
        }
        $this->save();
    }

    public function getPicture(){
        if ($this->picture){
            return $this->picture;
        }
        else return '/images/posts/default.png';
    }

    public function scopePublished($query)
    {
        return $query->where('status', 1);
    }
    public function scopeFeatured($query)
    {
        return $query->where('type', static::$TYPE_FEATURED_POST);
    }

    public function scopeSearch($query, $keywords)
    {
        return $query
            ->where('title_en', 'LIKE', '%' . $keywords . '%')
            ->orWhere('title_ar', 'LIKE', '%' . $keywords . '%')
            ->orWhere('body_ar', 'LIKE', '%' . $keywords . '%')
            ->orWhere('body_en', 'LIKE', '%' . $keywords . '%');
    }

    public static function publishedPercentage($days = 30)
    {
        $date = Carbon::now()->addDays(-$days);
        $publishedCount = static::where('created_at', '>=', $date->toDateString())->where('status', 1)->count();
        $count = static::where('created_at', '>=', $date->toDateString())->count();

        return compact('publishedCount', 'count');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use View;


class PostsController extends Controller
{
    function __construct()
    {
        Carbon::setLocale('ar');
        $allPosts = Post::published()->latest()->get();
        $groupedPosts = $allPosts->groupBy(function($e) {
            return Carbon::parse($e->created_at)->format('Y - m');
        });
        $categories = Category::whereHas('posts')->withCount('posts')->get();
        $featuredPosts = Post::featured()->published()->latest()->get();
        View::share(compact('allPosts', 'groupedPosts', 'featuredPosts', 'categories'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::published();

        if ($request->filled('category')) {
            $posts->whereHas('category', function ($query) use ($request) {
                $query->where('name_ar', 'like', $request->category);
            });
        }
        if ($request->filled('date')) {
            $parsedDate = Carbon::parse($request->date);
            $startDate = $parsedDate->toDateString();
            $afterMonth = $parsedDate->addMonth(1)->addDays(-1);
            $endDate = $afterMonth->toDateString();
            $posts->whereBetween('created_at', [$startDate, $endDate]);
        }
        if ($request->filled('search')) {
            $posts->search($request->search);
        }
        $posts = $posts->latest()->paginate(10);

        return view('posts.index', compact('posts'));
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $singlePost = Post::findOrFail($id);

        if ($singlePost->status != 1)
            abort(404);

        $prevPost = '';
        $nextPost = '';
        try{
            $previousId = Post::where('id', '<', $singlePost->id)->max('id');
            $prevPost = Post::find($previousId);
        }
        catch (Exception $e){

        }
        try{
            $nextId = Post::where('id', '>', $singlePost->id)->min('id');
            $nextPost = Post::find($nextId);
        }
        catch (Exception $e){

        }
        return view('posts.show', compact('singlePost', 'prevPost', 'nextPost'));
    }

}

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <!--  section  -->
    <section class="color-bg middle-padding ">
        <div class="wave-bg wave-bg2"></div>
        <div class="container">
            <div class="flat-title-wrap text-body-center">
                <h2><span>مدونة دكتوري</span></h2>
                <span class="section-separator"></span>
                <h4>هنا تعرض مقالاتنا واعلاناتنا وكل ما يتعلق بموقع دكتوري.</h4>
            </div>
        </div>
    </section>
    <section  id="sec1" class="middle-padding grey-blue-bg rtl">
        <div class="container">
            <div class="row">
                <!--blog content -->
                <div class="col-md-8">
                    <!--post-container -->
                    <div class="post-container fl-wrap">
                        @foreach ($posts as $post)
                            <!-- article> -->
                            <article class="post-article">
                                    <div class="list-single-main-media fl-wrap">
                                        <div class="single-slider-wrapper fl-wrap">
                                            <div class="single-slider fl-wrap"  >
                                                <div class="slick-slide-item"><img src="{{ $post->picture }}" alt=""></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="list-single-main-item fl-wrap">
                                        <div class="list-single-main-item-title fl-wrap">
                                            <h3><a href="{{ $post->path() }}">{{ $post->title_ar }}</a></h3>
                                        </div>
                                        <div class="post-body rtl-right-body">
                                            {!! $post->body_ar !!}
                                        </div>
                                        <div class="post-opt">
                                            <ul>
                                                <li><i class="fal fa-clock"></i> <span>{{ $post->created_at->diffForHumans() }}</span></li>
                                                <li><i class="fal fa-tags"></i> <span>{{ $post->getCategoryName() }}</span></li>
                                            </ul>
                                        </div>
                                        <span class="fw-separator"></span>
                                        <a href="{{ $post->path() }}" class="btn float-btn color-bg">اقرأ المزيد<i class="fal fa-angle-left"></i></a>
                                    </div>
                                </article>
                            <!-- article end -->
                        @endforeach

                        <div class="pagination-wrapper row text-center">
                            <div class="col-xs-12">
                                {{ $posts->appends(request()->input())->links() }}
                            </div>
                        </div>
                    </div>
                    <!--post-container end -->
                </div>
                <!-- blog content end -->
                <!--   sidebar  -->
                <div class="col-md-4">
                    @include('posts.nav')
                </div>
                <!--   sidebar end  -->
            </div>
        </div>
        <div class="limit-box fl-wrap"></div>
    </section>
    <!-- section end -->
@endsection

resources/views/posts/nav.blade.php
<!--box-widget-wrap -->
<div class="box-widget-wrap fl-wrap fixed-bar">
    <!--box-widget-item -->
    <div class="box-widget-item fl-wrap">
        <div class="box-widget">
            <div class="box-widget-content">
                <div class="box-widget-item-header">
                    <h3> ابحث في المدونة </h3>
                </div>
                <div class="search-widget">
                    <form action="/blog" class="fl-wrap">
                        <input name="search" id="se" type="text" class="search" placeholder="بـحـث.." value="{{ request('search') }}" />
                        <button type="submit" class="search-submit color2-bg" id="submit_btn"><i class="fal fa-search transition"></i> </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--box-widget-item end -->
    <!--box-widget-item -->
    <div class="box-widget-item fl-wrap">
        <div class="box-widget widget-posts">
            <div class="box-widget-content">
                <div class="box-widget-item-header">
                    <h3>المنشورات المميزة</h3>
                </div>
                @foreach ($featuredPosts as $post)
                    <!--box-image-widget-->
                        <div class="box-image-widget">
                            <div class="box-image-widget-media"><img src="{{ $post->picture }}" alt="">
                                <a href="{{ $post->path() }}" class="color-bg">تفاصيل</a>
                            </div>
                            <div class="box-image-widget-details">
                                <h4>{{ str_limit($post->title_ar, 40) }}</h4>
                                <div class="post-body rtl-right-body">{{ $post->body_ar }}</div>
                                <span class="widget-posts-date"><i class="fal fa-calendar"></i> {{ $post->created_at->diffForHumans() }} </span>
                            </div>
                        </div>
                        <!--box-image-widget end -->
                @endforeach
            </div>
        </div>
    </div>
    <!--box-widget-item end -->
    <!--box-widget-item -->
    <div class="box-widget-item fl-wrap">
        <div class="box-widget">
            <div class="box-widget-content">
                <div class="box-widget-item-header">
                    <h3> التصنيفات</h3>
                </div>
                <ul class="cat-item">
                    @foreach ($categories as $category)
                        <li><a href="{{ '/blog?' . http_build_query(['category' => $category->name_ar]) }}">{{ $category->name_ar }}</a> <span>{{ $category->posts_count }}</span></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    <!--box-widget-item end -->
</div>
<!--box-widget-wrap end -->

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('content')
    <!--  section  -->
    <section class="color-bg middle-padding ">
        <div class="wave-bg wave-bg2"></div>
        <div class="container">
            <div class="flat-title-wrap text-body-center">
                <h2><span>{{ $singlePost->title_ar }}</span></h2>
            </div>
        </div>
    </section>
    <section  id="sec1" class="middle-padding grey-blue-bg rtl">
        <div class="container">
            <div class="row">
                <!--blog content -->
                <div class="col-md-8">
                    <!--post-container -->
                    <div class="post-container fl-wrap">
                        <!-- article> -->
                        <article class="post-article">
                            <div class="list-single-main-media fl-wrap">
                                <div class="single-slider-wrapper fl-wrap">
                                    <div class="single-slider fl-wrap"  >
                                        <div class="slick-slide-item"><img src="{{ $singlePost->picture }}" alt=""></div>
                                    </div>
                                </div>
                            </div>
                            <div class="list-single-main-item fl-wrap">
                                <div class="list-single-main-item-title fl-wrap">
                                    <h3>{{ $singlePost->title_ar }}</h3>
                                </div>
                                <div class="post-body rtl-right-body">
                                    {!! $singlePost->body_ar !!}
                                </div>
                                <div class="post-opt">
                                    <ul>
                                        <li><i class="fal fa-clock"></i> <span>{{ $singlePost->created_at->diffForHumans() }}</span></li>
                                        <li><i class="fal fa-tags"></i> <span>{{ $singlePost->getCategoryName() }}</span></li>
                                    </ul>
                                </div>
                                <span class="fw-separator"></span>
                                <div class="post-nav fl-wrap">
                                    @if ($nextPost)
                                        <a href="{{ $nextPost->path() }}" class="post-link prev-post-link">
                                            <i class="fal fa-angle-left"></i>التالي<span class="clearfix">{{ $nextPost->title_ar }}</span>
                                        </a>
                                    @endif
                                    @if ($prevPost)
                                        <a href="{{ $prevPost->path() }}" class="post-link next-post-link">
                                            <i class="fal fa-angle-right"></i>السابق <span class="clearfix">{{ $prevPost->title_ar }}</span>
                                        </a>
                                    @endif
                                </div>
                            </div>
                            <!-- list-single-main-item -->
                        </article>
                        <!-- article end -->
                    </div>
                    <!--post-container end -->
                </div>
                <!-- blog content end -->
                <!--   sidebar  -->
                <div class="col-md-4">
                    @include('posts.nav')
                </div>
                <!--   sidebar end  -->
            </div>
        </div>
        <div class="limit-box fl-wrap"></div>
    </section>
    <!-- section end -->
@endsection